### ISSUE TITLE
add "mad science authors" category?

### ISSUE THREAD

**Issue by sidorares** [feross/mad-science-modules#3]
I'd probably list half of @mikolalysenko and half of @dominictarr modules here :)

**Comment by feross** [comment]
Yeah, this is a good idea. Can you send a PR?

**Comment by sidorares** [comment]
@feross done!

**Comment by dominictarr** [comment]
hey @sidorares has a few great things too, for example: https://github.com/sidorares/node-x11
anyone who implements a binary parser in JS is getting pretty hard core!

**Comment by sidorares** [comment]
@dominictarr #10 :)

**Comment by feross** [comment]
Merged :)
